accounts/urls.py
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
# from django.contrib.sitemaps.views import sitemap
# from .sitemaps import CabalahiSitemap

from django.contrib.auth.views import (
                                            LoginView, 
                                            LogoutView, 
                                            PasswordResetView, 
                                            PasswordResetDoneView, 
                                            PasswordResetConfirmView, 
                                            PasswordResetCompleteView,
                                        )

from .views import (
                    AboutSettingsView,
                    _PasswordChangeView,
                    ProfilePictureUploadView,
                    UserAccountUpdateView,
                    UserGeneralUpdateView,
                    UserProfileView,
                    UserDegreeUpdateView,
                    )


urlpatterns = [ 
    # <-------- SETTINGS_URLS ---------->
    url(r'^settings/account/$', UserAccountUpdateView.as_view(), name='settings_account'),
    url(r'^settings/about/$', AboutSettingsView.as_view(), name='settings_about'),
    url(r'^settings/password/$', _PasswordChangeView.as_view(), name='settings_password_change'),
    url(r'^settings/general/$', UserGeneralUpdateView.as_view(), name='settings_general'),
    url(r'^settings/degree/$', UserDegreeUpdateView.as_view(), name='settings_degree'),
    url(r'^settings/profile-picture/$', ProfilePictureUploadView.as_view(), name='settings_profile_picture'),
    url(r'^(?P<slug>[\w-]+)/$', UserProfileView.as_view(), name='profile'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

courses/urls.py
from django.conf.urls import url


from .views import (
    CourseListView,
    MyCoursesListView, 
    CourseDetailView, 
    # CourseCreateView, 
    # CourseUpdateView,
    # CourseDeleteView,
    LectureDetailView,
    CoursePurchaseView,
    ReviewView,
    signup_login_view,
    CreateCertificateView,
    GeneratePdf,
    MyCertificatesListView,
    )

urlpatterns = [
    url(r'^$', CourseListView.as_view(), name='list'),
    # url(r'^mis-certificados/$', MyCertificatesListView.as_view(), name='my-certificates'),
    url(r'^certificado/(?P<slug>[\w-]+)/$', GeneratePdf.as_view(), name='show-certificate'),
    url(r'^mis-cursos/$', MyCoursesListView.as_view(), name='my-courses'),
    url(r'^mis-certificados/$', MyCertificatesListView.as_view(), name='my-certificates'),
    url(r'^(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^signup-login/(?P<courseslug>[\w-]+)/$', signup_login_view, name='signup-login'),
    url(r'^(?P<slug>[\w-]+)/purchase/$', CoursePurchaseView.as_view(), name='purchase'),
    url(r'^(?P<slug>[\w-]+)/create-certificate/$', CreateCertificateView.as_view(), name='create-certificate'),


    url(r'^(?P<slug>[\w-]+)/review/$', ReviewView.as_view(), name='review'),
    url(r'^(?P<cslug>[\w-]+)/(?P<lslug>[\w-]+)/$', LectureDetailView.as_view(), name='lecture-detail'),

    # url(r'^(?P<slug>[\w-]+)/edit/$', CourseUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', CourseDeleteView.as_view(), name='delete'),
]

accounts/models.py
import datetime

from django.template.defaultfilters import date as _date
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse
# from django.contrib.sites.models import Site

from django.core.validators import RegexValidator
from django.core.mail import send_mail
from django.utils.text import slugify
from django.utils import timezone
from django.conf import settings
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField
# from sorl.thumbnail import ImageField
from courses.utils import unique_slug_generator

import uuid # Requerido para crear instancias únicas.

User = settings.AUTH_USER_MODEL
    

    # NINGUNO = 'Ninguno'
    # DOCTOR = 'Dr.'
    # TEC = 'Téc.'
    # ING = 'Ing.'
    # ARQ = 'Arq.'
    # LIC = 'Lic.'
    # MTR = 'Mtr.'
    # MBA = 'MBA'
    # MSC = 'M.Sc.'
    # MA = 'M.A.'
    # MJUR = 'M.Jur'
    # LLM = 'LL.M'
    # BCL = 'BCL'
    # OTHER = 'Otro'

    # ACADEMIC_OPTIONS = (
    #     (NINGUNO = 'Ninguno'),
    #     (DOCTOR = 'Dr.'),
    #     (TEC = 'Téc.'),
    #     (ING = 'Ing.'),
    #     (ARQ = 'Arq.'),
    #     (LIC = 'Lic.'),
    #     (MTR = 'Mtr.'),
    #     (MBA = 'MBA'),
    #     (MED = 'M.Ed'),
    #     (MSC = 'M.Sc'),
    #     (MA = 'M.A.'),
    #     (MJUR = 'M.Jur'),
    #     (LLM = 'LL.M.'),
    #     (BCL = 'BCL'),
    #     (OTHER = 'Otro'), 
    # )

GENDER_CHOICES = (
    ('hombre','hombre'),
    ('mujer', 'mujer'),
    ('otro', 'otro'),
)


def profile_picture_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/site_site-name/<filename>
    site_folder = unique_slug_generator(instance, instance.user_full_name())
    return 'accounts/{0}/{1}'.format(site_folder, filename)


class UserProfile(models.Model):
    user                            =   models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    degree                          =   models.CharField(_("Profesión o título académico"), max_length=100, blank=True, help_text='Escribe tu último título académico ej. "Doctorado en medicina", "Licenciatura en enfermería".')
    abbreviation                    =   models.CharField(_('Abreviatura de tu nivel académico'), max_length=20, blank=True, help_text='Ej. Dr. Lic. Ing. Mtr. Mba')
    academic_abbreviation_visible   =   models.BooleanField(_("Abreviatura de tu nivel académico visible"), default=False, help_text='La abreviatura de tu nivel académico será visible junto con tu nombre.')
    speciality                      =   models.CharField(_("Especialidad en tu profesión"), max_length=100, blank=True, help_text='Escribe la especialidad que desempeñas, si la posees.')
    gender                          =   models.CharField(_("Sexo"), max_length=6, blank=True, choices=GENDER_CHOICES)
    country                         =   models.CharField(_("País"), max_length=100, blank=True,)
    city                            =   models.CharField(_("Ciudad"), max_length=100, blank=True,)
    description                     =   models.TextField(_("Descripción"), max_length=2000, blank=True, null=True, help_text='Pequeña introducción de ti, máximo 2000 caracteres.')
    website                         =   models.URLField(_("Sitio web"), blank=True)
    birthday                        =   models.DateField(_("Fecha de nacimiento"), help_text='Agrega tu fecha de nacimiento para tener una mejor experiencia de usuario y para comprobar que eres mayor de 13 años, de lo contrario tu cuenta puede ser bloqueada.', null=True, blank=True)
    phone                           =   PhoneNumberField('Teléfono ej. +503 2502 6108', blank=True)
    whatsapp                        =   PhoneNumberField('WhatsApp ej. +503 7390 5006', blank=True)
    # image                           =   models.ImageField(upload_to=site_user_image_directory_path, blank=True)
    # profile_picture                 =   models.ImageField(upload_to=site_user_image_directory_path, blank=True)
    profile_picture                 =   models.ImageField(upload_to=profile_picture_directory_path, blank=True)
    # banner              =   models.ImageField(upload_to='banner_image', blank=True)
    last_updated                    =   models.DateTimeField(auto_now_add=True)
    views                           =   models.PositiveIntegerField(default=0, blank=True)
    is_instructor                   =   models.BooleanField(default=False)
    slug                            =   models.SlugField(_("URL del perfil"), max_length=255, null=True, blank=True, help_text='URL personalizada para el perfil.')

    def __str__(self):
        return self.user_full_name()

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = "Perfiles"

    def get_absolute_url(self):
        return reverse('accounts:profile', kwargs={'slug': self.slug}) 

    def user_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        if self.abbreviation:
            full_name = '%s %s %s' % (self.abbreviation, self.user.first_name, self.user.last_name)
        else:
            full_name = '%s %s' % (self.user.first_name, self.user.last_name)
        return full_name.strip()

    def full_profile(self):
        score = 0
        if self.user.first_name:
            score += 10
        if self.user.last_name:
            score += 10
        if self.user.email:
            score += 10
        if self.birthday:
            score += 10
        if self.gender:    
            score += 10
        if self.country:
            score += 10
        if self.city:
            score += 10
        if self.profile_picture:
            score += 10
        if self.phone:
            score += 10
        if self.description:
            score += 10
        return score

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slug_generator(self, self.user_full_name())
        super().save()


class CityOption(models.Model):
    city_name           =   models.CharField(_('Nombre de la ciudad'), max_length=100, blank=True)
    postal_code         =   models.CharField(_('Código postal'), max_length=20, blank=True)
    state               =   models.CharField(_('Estado, provincia o departamento'), max_length=100, blank=True)
    country             =   models.CharField(_('País'), max_length=100, blank=True)
    address_region      =   models.CharField(_('Región usando el formato ISO 3166-1 Ej. SV, AR, MX.'), max_length=20, blank=True)

    def __str__(self):
        return self.city_name

    class Meta:
        ordering = ['city_name']
        verbose_name = 'Ciudad'
        verbose_name_plural = "Ciudades"


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_= kwargs['instance']
        # slug_ = unique_slug_generator(user_.slug)
        user_profile = UserProfile.objects.create(user=user_)
        
post_save.connect(create_profile, sender=User)

accounts/forms.py
from PIL import Image, ImageOps
from django import forms
from django.contrib.auth import get_user_model
from .models import UserProfile
from django.utils.translation import ugettext_lazy as _
User = get_user_model()

class UserEditForm(forms.ModelForm):
        # email = forms.EmailField()
        # category = forms.CharField(required=False, validators=[validate_category])
        class Meta:
            model = User
            fields = [ 
                        'first_name',
                        'last_name',
                        'email',
                        'username',
                        ]

            labels = {
                        'first_name': 'Primer nombre',
                        'last_name': 'Primer apellido',
                        'username': 'Nombre de usuario para Iniciar Sesión',
                    }

class UserGeneralSettingsEditForm(forms.ModelForm):
        # city    =   forms.ModelChoiceField(queryset=CityOptions.objects.all(), label = "Ciudad", to_field_name="city_name")

    class Meta:
        model = UserProfile
        fields  = [  
                    'birthday',
                    'phone',
                    'whatsapp',
                    'website',
                    'gender',
                    'country',
                    'city',
                    ]
        # # labels = {
        # #         'site_name': 'Nombre de tu Sucursal Digital',
        # #         'phone': 'Teléfono principal ej. +503 2502 6108',
        # #         'city': 'Ciudad',
        # #     }
        # widgets = {
        #     'site_keywords_tag': forms.Textarea(attrs={'rows': 2}),
        #     'site_description_tag': forms.Textarea(attrs={'rows': 4}),
        #     }
        # help_texts={'phone':'Prefijo internacional + código de área + número. Ej. +503 2502 6108'}
        error_messages = {
            'phone': {
                'invalid': "Ingresa un número de teléfono válido Ej. +503 2502 6108"
            },
            'whatsapp': {
                'invalid': "Ingresa un número de teléfono válido Ej. +503 7390 5006"
            }
        }


class UserDegreeSettingsEditForm(forms.ModelForm):
        # city    =   forms.ModelChoiceField(queryset=CityOptions.objects.all(), label = "Ciudad", to_field_name="city_name")

    class Meta:
        model = UserProfile
        fields  = [  
                    'degree',
                    'speciality',
                    'abbreviation',
                    'academic_abbreviation_visible',
                    ]
     

# class ProfilePictureForm(forms.ModelForm):
#     profile_picture = forms.ImageField(label=_('Actualizar foto de perfil:'),required=False, error_messages = {'invalid':_("Solo formatos de imagen válidos .PNG o .JPG")}, widget=forms.FileInput)
#     remove_photo = forms.BooleanField(label=_('Eliminar foto'), required=False) #REMOVED BECAUSE DIGITAL OCEAN SPACES

#     class Meta:
#         model  = UserProfile
#         fields = ['profile_picture',]

#     def save(self, commit=True):
#         _form = super(ProfilePictureForm, self).save()
#         if self.cleaned_data.get('profile_picture'):
#             try:
#                 image = Image.open(_form.profile_picture)
#                 width, height = image.size
#                 new_height = 300
#                 new_width = new_height * width / height
#                 size = (300, new_height * width / height)
#                 # resized_image = image.resize((int(new_width), int(new_height)), Image.ANTIALIAS)
#                 resized_image = ImageOps.fit(image, (300, 300), Image.ANTIALIAS)
#                 resized_image.save(_form.profile_picture.path, optimize=True, quality=85)
#             except:
#                 pass
        
#         if self.cleaned_data.get('remove_photo'):   
#             try:
#                 os.unlink(_form.profile_picture.name)
#             except OSError:
#                 pass
#             _form.profile_picture = None
#         if commit:
#             _form.save()
#         return _form

class ProfilePictureForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    profile_picture = forms.ImageField(label=_('Actualizar foto de perfil:'),required=False, error_messages = {'invalid':_("Solo formatos de imagen válidos .PNG o .JPG")}, widget=forms.FileInput)


    class Meta:
        model  = UserProfile
        fields = ('profile_picture', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(ProfilePictureForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.profile_picture)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
        print(resized_image)
        resized_image.save(photo.profile_picture.path)

        return photo


class AboutForm(forms.ModelForm):

        class Meta:
            model = UserProfile
            fields  = [  
                        'description',
                        ]
            widgets = {
                    'description': forms.Textarea(attrs={'rows': 15}),

                }

accounts/templates/accounts/edit/edit_account.html
{% extends 'accounts/edit/base_edit.html' %}
{% load static %}
{% load custom_filters %}

{% block stylesheet %}
    <!-- BOOTSTRAP-SELECT -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.0-beta/css/bootstrap-select.min.css">
    <!-- BOOTSTRAP-DATEPICKER -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css">
{% endblock stylesheet %}

{% block content%}
    <div class="h-700 mb-5">
        <h3>{{ title }}</h3>    
        <div class="dropdown-divider"></div>
        <p class="mb-4">
            <small class="text-muted">{{ instructions }}</small>
        </p>

        <div class="card card-shadow-soft mb-3 border-top-0 border-right-0 border-left-0 text-dark">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data" id="formUpload" novalidate="">
                    {% csrf_token %}
                    {% include 'includes/form_accounts.html' %}

                    {% if title == 'Credenciales' %}
                        <div class="form-group">
                            <label class="mt-1">Contraseña:</label>
                            <p>Puedes cambiar tu contraseña ingresando a este <a href="{% url 'accounts:settings_password_change'%}" class="btn btn-outline-dark btn-sm">link</a></p>
                        </div>
                    {% endif %}

                    <div class="mt-4 text-right" role="group">
                        <button type="submit" class="btn btn-primary btn-lg">Guardar</button>
                    </div>
                </form>      
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <!-- SELECT PICKER -->
    <script src="{% static 'js/select-picker.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/locales/bootstrap-datepicker.es.min.js"></script>

    <script type="text/javascript">
        $('#id_birthday').datepicker({
            startView: 2,
            language: "es",
            autoclose: true,
            defaultViewDate: "01-01-1980",
            startDate: "01-01-1920",
            endDate: "01-01-2005",
            format: "dd-mm-yyyy",
        });
    </script>
{% endblock javascript %}

accounts/templates/accounts/edit/edit_profile_picture.html
{% extends 'accounts/edit/base_edit.html' %}
{% load static %}
{% load custom_filters %}
 
{% block col_edit_form %}
    <div class="col-12 col-md-5 py-3 text-dark">
{% endblock col_edit_form %}

{% block content%}
    <div class="h-700 mb-5">
        <h3>{{ title }}</h3>
        <div class="dropdown-divider"></div>
        <p class="mb-4">
            <small class="text-muted">{{ instructions }}</small>
        </p>
        <div class="card card-shadow-soft mb-3 border-top-0 border-right-0 border-left-0 text-dark">
          <div class="card-body">
            {% if request.user.userprofile.profile_picture %}
              <p>Foto de perfil actual:</p>
              <img src="{{request.user.userprofile.profile_picture.url}}" class="img-thumbnail thumbnail-size-200 mb-3">
            {% endif %} 

            <form method="POST" enctype="multipart/form-data" id="formUpload">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group text-dark">
                 {% comment %}
                   
                    {% if forloop.last %}
                      {% if request.user.userprofile.profile_picture %}
                        <div class="custom-control custom-checkbox d-block my-3">
                          {{ field|addclass:'custom-control-input' }}
                          <label class="custom-control-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                        </div>
                      {% endif %}
                    {% else %}
                      {{ field.label_tag }}
                      {{ field|addclass:"form-control" }}
                    {% endif %}
                 {% endcomment %}
                    {% if field.auto_id == 'id_profile_picture' %}
                      {{ field.label_tag }}
                      {{ field|addclass:"form-control" }}
                    {% else %}
                      {{ field|addclass:"form-control" }}
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary btn-lg mt-2 float-right cursor-pointer">
                    Guardar
                </button>
            </form>

              <div class="modal fade" id="modalCrop">
                  <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                          <div class="modal-header">
                              <h4 class="modal-title">
                                  Recortar foto
                              </h4>

                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>

                          </div>
                          <div class="modal-body p-5">
                              <img src="" id="image" style="max-width: 100%;">
                          </div>
                          <div class="modal-footer">
                              <div class="btn-group pull-left" role="group">
                                  <button type="button" class="btn btn-outline-secondary js-zoom-out">
                                      <i class="fas fa-minus"></i>
                                  </button>
                                  <button type="button" class="btn btn-outline-secondary js-zoom-in">
                                      <i class="fas fa-plus"></i>
                                  </button>
                              </div>
                              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                              <button type="button" class="btn btn-primary js-crop-and-upload">Guardar</button>
                          </div>    
                      </div>
                  </div>
              </div>
          </div>
        </div>
    </div>
</div><!-- END COL -->
{% endblock %}

{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
    <script src="{% static 'js/upload-icon-submit.js' %}"></script>

  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_profile_picture").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 300,
          minCropBoxHeight: 300,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock javascript %}

accounts/templates/accounts/edit/edit_site_about_section.html
{% extends 'accounts/edit/base_edit.html' %}
{% load static %}
{% load custom_filters %}
{% block message %}{% comment %}Overwrite message block{% endcomment %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{message.tags}}{% endif %} alert-dismissible fade show text-center rounded-0 mb-0 w-100" role="alert">
                <span class="d-inline-block mb-0 align-middle mb-0">{{ message|safe }}</span>
            </div>
        {% endfor %}                          
    {% endif %}
{% endblock message %}
{% block content%}
        <h3>{{ title }}</h3>    
        <div class="dropdown-divider"></div>
         <p class="mb-4">
            <small class="text-muted">{{ instructions }}</small>
        </p>
        {% comment %}   NO FUNCIONA PORQUE BORRA LOS OTROS CAMPOS AL SUBIRSE         
            <div class="card card-shadow-soft border-0 text-dark mt-4">
                <div class="card-body">
                    {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
                    <input class="fileupload" type="file" name="about_image" multiple
                           style="display: none;"
                           data-url="{% url 'sites:settings_about' %}"
                           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

                    {# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #}
                    <div class="mb-4">           
                            <label for="id_about_image" class="d-block">Imagen de la sección Acerca de:</label>
                            <div  class="js-current-image">
                              {% if object.about_image %}<img src="{{ object.about_image.url }}" class='img-thumbnail w-75 d-block mx-auto mb-4'>{% endif %} 
                            </div>
                    </div>    

                    <div class="d-flex justify-content-between ">
                        {% if request.user.cabalahisite.about_image %}
                            <button type="button" class="btn btn-outline-secondary btn-lg" data-toggle="modal" data-target="#exampleModal">
                                Eliminar
                            </button>
                        {% endif %}
                            <button type="button" class="btn btn-outline-primary btn-lg js-upload-photos">
                                Actualizar imagen
                            </button>
                    </div>   
                </div>
            </div>
        {% endcomment %}

         <div class="card card-shadow-soft mt-4 border-0 text-dark">
            <div class="card-body">

       
                <form method="POST" enctype="multipart/form-data" id="formUpload">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                <small><p {% if forloop.last %} class="mb-0" {% endif %}>{{ error }}</p></small>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% for field in form %}              
                        <div class="form-group mb-4">                                       
                            
                            {{ field.label_tag }}
                            {{ field|add_validation_class }}
                 

                            {% for error in field.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-lg mt-4 float-right">Guardar</button>
                </form>      
            </div>
        </div>
    {% comment %}        
        {% include 'includes/edit_modal_delete_image.html'%}
    {% endcomment %}
{% endblock %}

{% block javascript %}{% endblock javascript %}