courses/urls.py
from django.conf.urls import url


from .views import (
    CourseListView,
    MyCoursesListView, 
    CourseDetailView, 
    # CourseCreateView, 
    # CourseUpdateView,
    # CourseDeleteView,
    LectureDetailView,
    CoursePurchaseView,
    ReviewView,
    signup_login_view,
    CreateCertificateView,
    GeneratePdf,
    MyCertificatesListView,
    )

urlpatterns = [
    url(r'^$', CourseListView.as_view(), name='list'),
    # url(r'^mis-certificados/$', MyCertificatesListView.as_view(), name='my-certificates'),
    url(r'^certificado/(?P<slug>[\w-]+)/$', GeneratePdf.as_view(), name='show-certificate'),
    url(r'^mis-cursos/$', MyCoursesListView.as_view(), name='my-courses'),
    url(r'^mis-certificados/$', MyCertificatesListView.as_view(), name='my-certificates'),
    url(r'^(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^signup-login/(?P<courseslug>[\w-]+)/$', signup_login_view, name='signup-login'),
    url(r'^(?P<slug>[\w-]+)/purchase/$', CoursePurchaseView.as_view(), name='purchase'),
    url(r'^(?P<slug>[\w-]+)/create-certificate/$', CreateCertificateView.as_view(), name='create-certificate'),


    url(r'^(?P<slug>[\w-]+)/review/$', ReviewView.as_view(), name='review'),
    url(r'^(?P<cslug>[\w-]+)/(?P<lslug>[\w-]+)/$', LectureDetailView.as_view(), name='lecture-detail'),

    # url(r'^(?P<slug>[\w-]+)/edit/$', CourseUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', CourseDeleteView.as_view(), name='delete'),
]

saludemy/urls.py
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import (
                                        LoginView, 
                                        LogoutView, 
                                        PasswordResetView, 
                                        PasswordResetDoneView, 
                                        PasswordResetConfirmView, 
                                        PasswordResetCompleteView,
                                        )
from courses.views import (
                            HomeView,
                            signup_form_step_1,
                            signup_form_step_2,
                            )
# from categories import views as categories_views
# from cabalahi_sites import views as cabalahi_sites_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(template_name = "home.html"), name='home'),
    url(r'^login/$', LoginView.as_view(
                                        redirect_authenticated_user=True, 
                                        template_name='registration/login.html'
                                        ), 
                                        name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reset/$', PasswordResetView.as_view(
                                            email_template_name='registration/password_reset_email.html',
                                            subject_template_name='registration/password_reset_subject.txt'
                                        ),
                                        name='password_reset'),
    url(r'^reset/done/$', PasswordResetDoneView.as_view(
                                        template_name='registration/password_reset_done.html'
                                        ),
                                        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                                PasswordResetConfirmView.as_view(
                                        template_name='registration/password_reset_confirm.html'
                                        ),
                                        name='password_reset_confirm'),
    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(
                                        template_name='registration/password_reset_complete.html'),
                                        name='password_reset_complete'),
    url(r'^signup/$', signup_form_step_1, name='signup'),
    url(r'^signup-step-2/$', signup_form_step_2, name='signup_step_2'),

    url(r'^dashboard/', TemplateView.as_view(template_name = "old_dashboard.html"), name='dashboard'),
    url(r'^cursos/', include('courses.urls', namespace='courses')),
    url(r'^a/', include('accounts.urls', namespace='accounts')),
    url(r'^curso/detalle', TemplateView.as_view(template_name = "course_detail.html"), name='detail'),
    url(r'^curso/leccion', TemplateView.as_view(template_name = "course_lesson.html"), name='lesson'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/views.py
import random
import datetime
from io import BytesIO
from django.db.models import Avg
from django.core.files import File
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import get_user_model, login, authenticate
from django.db.models import Prefetch, Q, Count
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from .utils import render_to_pdf 
from django.contrib.auth.forms import (
    AuthenticationForm,)
from django.http import Http404, HttpResponse, FileResponse

# from weasyprint import HTML, CSS

from django.views.generic import (
        CreateView,
        DetailView,
        ListView,
        UpdateView,
        DeleteView,
        RedirectView,
        FormView,
        View,
    )

#from .forms import VideoForm
# from analytics.models import CourseViewEvent
# from videos.mixins import MemberRequiredMixin, StaffMemberRequiredMixin
from categories.models import Category
from .forms import CourseForm, SignupFormStep1,SignupFormStep2, ReviewForm, SignUpForm
from .models import Course, Lecture, MyCourses, Topic, Review, Certificate, MyLecture


def signup_form_step_1(request):
    if request.user.is_authenticated():
        return redirect(reverse_lazy('courses:list'))
    if request.method == 'POST':
        form = SignupFormStep1(request.POST or None)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect(reverse('signup_step_2'))
        else:
            form = SignupFormStep1(request.POST)
    else:
        form = SignupFormStep1()
    context = {
        "form": form,
        "title": 'Regístrate en la comunidad de formación en salud y bienestar',
        "step_1": True,
    }
    return render(request, 'registration/signup.html', context)


@login_required
def signup_form_step_2(request):
    if request.user.first_name:
            return redirect(reverse_lazy('courses:list'))
    if request.method == 'POST':
            form = SignupFormStep2(request.POST or None)
            if form.is_valid():
                user = request.user
                user.first_name = form.cleaned_data.get('first_name')
                user.last_name = form.cleaned_data.get('last_name')
                user.email = form.cleaned_data.get('email')
                user.save()
                return redirect(reverse('courses:list'))
            else:
                form = SignupFormStep2(request.POST)
    else:
        form = SignupFormStep2()
    context = {
            "form": form,
            "step": 'Paso 2',
            "title": 'Información para tu cuenta',
        }
    return render(request, 'registration/signup.html', context)


class HomeView(ListView):
    def get(self, request, *args, **kwargs): # GET -- retrieve view / list view / search
        if self.request.user.is_authenticated():
            return redirect('courses:list')
        course_list = Course.objects.annotate(
            avg_rating=Avg('review__rating')
            )
        context = {
            "course_list": course_list,
        }
        return render(request, "home.html", context)
        

class CourseListView(LoginRequiredMixin, ListView):
    template_name = 'courses/dashboard.html'
    paginate_by = 12

    def get_context_data(self, *args, **kwargs):
        context = super(CourseListView, self).get_context_data(*args, **kwargs)
        # print(dir(context.get('page_obj')))
        user = self.request.user
        context['categories_list'] = Category.objects.all()
        context['title'] = 'Cursos para ti'
        context['owned'] = user.mycourses
        context['my_certificates'] = user.certificate_set.all().count()
        return context

    def get_queryset(self):
        request = self.request
        qs = Course.objects.all().annotate(
            avg_rating=Avg('review__rating'),
            rating_num=Count('review')
            )
        query = request.GET.get('q')
        user = self.request.user
        if query:
            qs = qs.filter(title__icontains=query)
        if user.is_authenticated():
            qs = qs.owned(user)
        return qs


class MyCoursesListView(LoginRequiredMixin, ListView):
    template_name = 'courses/dashboard.html'
    paginate_by = 12

    def get_context_data(self, *args, **kwargs):
        context = super(MyCoursesListView, self).get_context_data(*args, **kwargs)
        # print(dir(context.get('page_obj')))
        user = self.request.user
        context['categories_list'] = Category.objects.all()
        context['title'] = 'Mis cursos'
        context['owned'] = user.mycourses
        context['my_certificates'] = user.certificate_set.all().count()
        return context

    def get_queryset(self):
        user = self.request.user
        qs = Course.objects.filter(owned__user=user).owned(user)
        return qs


class MyCertificatesListView(LoginRequiredMixin, ListView):
    template_name = 'courses/certificates.html'
    paginate_by = 12

    def get_context_data(self, *args, **kwargs):
        context = super(MyCertificatesListView, self).get_context_data(*args, **kwargs)
        # print(dir(context.get('page_obj')))
        user = self.request.user
        context['categories_list'] = Category.objects.all()
        context['title'] = 'Mis certificados'
        context['owned'] = user.mycourses
        context['my_certificates'] = user.certificate_set.all().count()
        return context

    def get_queryset(self):
        user = self.request.user
        qs = Certificate.objects.filter(user=user)
        return qs


class CoursePurchaseView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, slug=None):
        qs = Course.objects.filter(slug=slug).owned(self.request.user)
        if qs.exists():
            user = self.request.user
            if user.is_authenticated():
                my_courses = user.mycourses
                print(my_courses)
                print(my_courses)
                print(my_courses)
                print(my_courses)
                # run transaction
                # if transaction successful:
                my_courses.courses.add(qs.first())
                return qs.first().lecture_set.first().get_absolute_url()
            return qs.first().lecture_set.first().get_absolute_url()
        return "/courses/"


class CreateCertificateView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, slug=None):
        course = Course.objects.filter(slug=slug).owned(self.request.user).first()
        if course:
            user = self.request.user
            if user.is_authenticated():
                certificate_exists, new_certificate = Certificate.objects.get_or_create(user=self.request.user, course=course)
                if new_certificate:
                    obj = Certificate.objects.get(user=self.request.user, course=course)                    
                    context = {'instance': obj}
                    pdf = render_to_pdf('courses/certificate_pdf_template.html', context)
                    print("1")
                    print("1")
                    print("1")
                    filename = "certificado-{}-{}.pdf".format(course.slug, obj.slug)
                    obj.pdf.save(filename, File(BytesIO(pdf.content)))
                return course.get_absolute_url()
                print("2")
                print("2")
                print("2")
            return course.get_absolute_url()
        return "/courses/"


class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        try:
            course = Course.objects.filter(slug=self.kwargs['slug']).owned(self.request.user).first()
            obj = Certificate.objects.get(user=self.request.user, course=course)
            pdf = obj.pdf.path
            if self.request.GET.get('download'):
                # response = HttpResponse(open(pdf, 'rb'), content_type='application/pdf')
                response = FileResponse(open(pdf, 'rb'), content_type='application/pdf')
                response['Content-Disposition'] = 'attachment; filename="{}"'.format(obj.pdfname)
                return response
            return FileResponse(open(pdf, 'rb'), content_type='application/pdf')
        except FileNotFoundError:
            raise Http404()


@method_decorator(login_required, name='dispatch')
class LectureDetailView(View):
    def get(self, request, cslug=None, lslug=None, *args, **kwargs):
        obj = None
        qs = Course.objects.filter(slug=cslug).lectures().reviews().owned(request.user)
        # qs = Course.objects.filter(slug=cslug).topics().owned(self.request.user)
        if not qs.exists():
            raise Http404
        course_ = qs.first()
        # if request.user.is_authenticated():
        #     view_event, created = CourseViewEvent.objects.get_or_create(user=request.user, course=course_)
        #     if view_event:
        #         view_event.views += 1
        #         view_event.save()
        lectures_qs = course_.lecture_set.filter(slug=lslug)
        if not lectures_qs.exists():
            raise Http404
        obj = lectures_qs.first()
        # lectures = Topic.objects.get(title=obj.topic).lecture_set.all()
        lectures = Lecture.objects.filter(topic=obj.topic).lecture_seen(user=request.user, topic=obj.topic)
        # print('LECTURES')
        # print('LECTURES')
        # print('LECTURES')
        # print len("-------------------")
        # print(lectures.query)
        # for lecture in lectures:

courses/templates/courses/certificate_pdf_template.html
 {% load static %}
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Certificado {{instance.course}} {{instance.user.get_full_name}}</title>
        <style>
        @page {
            size: letter landscape;            
            @frame col1_frame {
            left: 42pt; width: 707pt; top:42pt; height: 525pt; border: 2pt solid #ede3c1; padding-top: 50px;
            /*-pdf-frame-border: 1;    /* for debugging the layout */
            }
        }
        @font-face {
          font-family: "Roboto";
          src: url("{% static 'fonts/Roboto-Regular.tff' %}");
          src: url("/static/fonts/roboto.ttf");
        }
         @font-face {
          font-family: "parisienne-regular";
          src: url("{% static 'fonts/parisienne-regular.tff' %}");
          src: url("/static/fonts/parisienne-regular.ttf");
        }
        h1{
            font-size: 40px;
            margin: 0;
            padding: 0;
            text-align: center;
            color:#283973!important; 
        }
        h2{
           font-size: 45px;
           font-weight: bold;
            margin: 0;
            padding: 0;
            text-align: center;
            color:#8d6e4c!important;  
            font-family: 'parisienne-regular';   
        }
        .text-center{
            text-align: center;
        }
        p{
           font-size: 20px;
            margin: 20px 0;
            padding: 0;
            text-align: center;
            line-height: 0px;
            color:#8d6e4c!important;  
        }
        h6{
            font-size: 40px;
            padding: 0;
            text-align: center;
            line-height: 45px;
 
            color:#8d6e4c!important;  
        }
        .logo-size{
            width:175px;
            height: auto;
            display: block;
        }
        body {
          font-family: "Roboto";
        }
        .border{
            border: 1px solid black; 
        }
        .w-440{}
        </style>
    </head>
    <body>
         <table style="height:450px;  margin-top:100px;">
            <tr style="display:block;">
                <td style="width:440px; padding-left:15px;">
                    <img style="height:auto;" src="{% static 'medal-certificate-saludemy.jpg' %}">
                </td>
                <td style="padding:30px;">
                    <h1 class="">Certificado de cumplimiento</h1>
                    <h2>{{instance.user.get_full_name}}</h2>
                    <p class="text-center">Por participar y aprobar el curso</p>
                    <h6 class="text-center">{{instance.course}}</h6>
                </td>
            </tr>
         </table>
         <table  style="text-align:center;  height:100px;">
            <tr style="display:block;">
                <td><img class="logo-size" src="{% static 'firma1-certificate.png' %}"></td>
                <td><img class="logo-size" src="{% static 'firma2-certificate.png' %}"></td>
                <td><img class="logo-size" src="{% static 'colegiomedicologo.png' %}"></td>
                <td><img class="logo-size" src="{% static 'saludemygris.png' %}"></td>
            </tr>
        </table>
    </body>
</html>

courses/templates/courses/certificate_pdf_templateV0.html
 {% load static %}
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style>
        @page {
            size: letter landscape;
            @frame col1_frame {             /* Content frame 1 */
            left: 60pt; width: 225pt; top: 125pt; height: 300pt; border: 4pt solid #8d6e4c;  border-radius: 25px;
            /*-pdf-frame-border: 1;    /* for debugging the layout */
        }
            @frame col2_frame {             /* Content frame 2 */
                left: 300pt; width: 450pt; top: 125pt; height: 300pt; 
             /*  -pdf-frame-border: 1;   /* for debugging the layout */
            }
           @frame col3_frame {             /* Content frame 2 */
                left: 60pt; width: 100pt; top: 425pt; height: 80pt; 
                /*-pdf-frame-border: 1;   /* for debugging the layout */
            }
            @frame col4_frame {             /* Content frame 2 */
                left: 225pt; width: 125pt; top: 425pt; height: 80pt; 
                /*-pdf-frame-border: 1;   /* for debugging the layout */
            }
            @frame col5_frame {             /* Content frame 2 */
                left: 410pt; width: 175pt; top: 425pt; height: 50pt; 
                /*-pdf-frame-border: 1;   /* for debugging the layout */
            }
            @frame col6_frame {             /* Content frame 2 */
                left: 590pt; width: 120pt; top: 425pt; height: 50pt; 
                /*-pdf-frame-border: 1;   /* for debugging the layout */
            }
        }
        @font-face {
          font-family: "Roboto";
          src: url("{% static 'fonts/Roboto-Regular.tff' %}");
          src: url("/static/fonts/roboto.ttf");

        }
         @font-face {
          font-family: "parisienne-regular";
          src: url("{% static 'fonts/parisienne-regular.tff' %}");
          src: url("/static/fonts/parisienne-regular.ttf");

        }
        h1{
            font-size: 40px;
            margin: 0;
            padding: 0;
            text-align: center;
            color:#283973!important; 
        }
        h2{
           font-size: 45px;
           font-weight: bold;
            margin: 0;
            padding: 0;
            text-align: center;
            color:#8d6e4c!important;  
            font-family: 'parisienne-regular';   
        }
        .text-center{
            text-align: center;
        }
        p{
           font-size: 20px;
            margin: 0;
            padding: 0;
            text-align: center;
            line-height: 10px;
            color:#8d6e4c!important;  
        }
        .course-name{
            font-size: 40px!important;
            margin: 0;
            padding: 0;
            text-align: center;
            line-height: 55px;
            color:#8d6e4c!important;  
        }
        .img-size{
            width:300px;
            height:auto;
            border: 1px solid black;

        }
        .logo-size{
            width:220px;
            height: auto;
            display: block;
        }
        body {
          font-family: "Roboto";
        }
        </style>
    </head>
    <body>
       
        <img class="img-size" src="{% static 'medal-certificate-saludemy.png' %}">
        <h1 class="title">Certificado de cumplimiento</h1>
        <h2>Javier Orlando Mena Velásquez</h2>
        <p class="text-center">Por participar y aprobar el curso</p>
        <h6 class="text-center course-name">Marketing Médico: Cómo atraer pacientes a mi clínica</h6>
        <img  class="logo-size" src="{% static 'firma1-certificate.png' %}">
        <img  class="logo-size" src="{% static 'firma2-certificate.png' %}">
        <img  class="logo-size" src="{% static 'colegiomedicologo.png' %}">
        <img  class="logo-size" src="{% static 'saludemygris.png' %}">
       
    </body>
</html>

courses/templates/courses/certificates.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
        {% if user.is_authenticated %}
            <!--  HOME SECTION  -->
            <header class="bg-brand py-4 shadow" style="background:url('{% static "brand-background.svg" %}') no-repeat; background-position-x: right;
            background-position-y: middle;">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 col-md-7">
                            <div class="d-flex flex-row justify-content-center justify-content-md-start">
                                {% if user.userprofile.profile_picture %}
                                    <a href="{{ user.userprofile.get_absolute_url }}" >
                                        <img src="{{ user.userprofile.profile_picture.url }}" alt="{{ user.user_full_name }}" class="rounded-circle profile-no-picture-medium">
                                    </a>
                                {% else %}
                                    <a href="{{ user.userprofile.get_absolute_url }}" class="text-white bg-secondary rounded-circle profile-no-picture-medium d-inline-block text-decoration-none">{% if not user.first_name %}{{user.username|slice:":1"}}{% else %}{{user.first_name|slice:":1"}}{% endif %}</a>
                                {% endif %}
                                <div class="ml-3 d-inline-block my-auto">
                                    <h3 class="text-white d-inline-block">{% if not request.user.userprofile.user_full_name %}{{user.username}}{% else %}{{request.user.userprofile.user_full_name}}{% endif %}</h3>
                                    {% if request.user.userprofile.speciality %}
                                        <p class="small text-white d-block mb-0">{{request.user.userprofile.speciality}}</p>
                                    {% endif %}    
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="text-center pt-2">
                                <div class="d-inline-block my-auto">
                                    <h3 class="text-white d-inline-block mb-1">1</h3>
                                    <p class="small text-white d-block mb-0">Cursos en progreso</p>
                                </div>
                            </div>    
                        </div>
                        <div class="col-md-1">
                            <div class="text-center pt-2">
                                <a href="{% url 'courses:my-certificates' %}" class="d-inline-block my-auto">
                                    <h3 class="text-white d-inline-block mb-1">{{my_certificates}}</h3>
                                    <p class="small text-white d-block mb-0">Mis <br/>certificados</p>
                                </a>
                            </div>    
                        </div>
                        <div class="col-md-1">
                            <div class="text-center pt-2">
                                <a href="{% url 'courses:my-courses' %}" class="d-inline-block my-auto">
                                    <h3 class="text-white d-inline-block mb-1">{{owned}}</h3>
                                    <p class="small text-white d-block mb-0">Mis <br/>cursos</p>
                                </a>
                            </div>    
                        </div>
                        <div class="col-md-1">
                            <div class="text-center pt-2">
                                <div class="d-inline-block my-auto">
                                    <h3 class="text-white d-inline-block mb-1">3</h3>
                                    <p class="small text-white d-block mb-0">Insignias <br/>obtenidas</p>
                                </div>
                            </div>    
                        </div>
                        <div class="col-md-1">
                            <div class="text-center pt-2">
                                <div class="d-inline-block my-auto">
                                    <h3 class="{% if request.user.userprofile.full_profile < 50 %}
                                                text-danger
                                                {% elif request.user.userprofile.full_profile < 90 %}
                                                text-warning
                                                {% else %}
                                                text-success
                                                {% endif %}
                                    d-inline-block mb-1">{{request.user.userprofile.full_profile}}%</h3>
                                    <p class="small text-white d-block mb-0">Perfil completo</p>
                                </div>
                            </div>    
                        </div>
                    
                    </div>
                </div>
            </header>
        {% endif %}
{% comment %}
    <section id="conversion" class="flex-grow mb-4 bg-white shadow py-5">   
        <div class="container-fluid">
            <div class="row" >        
                <div class="col-4">
                    <h3 class="brand-text d-inline-block">Programas y cursos</h3>
                </div>
                <div class="col-8">
                    <div class="input-group w-100">
                        <input type="search" id="search-input" placeholder="¿Qué deseas aprender?" class="form-control bg-light border-0 rounded-0 py-3" value="{% if category_name %}{{category_name}}{% endif %}" />
                        <span class="input-group-append">
                            <button class=" disabled btn btn-secondary" type="button">
                                <img class="border-0 rounded-0" src="{% static 'icons/search_icon_white.svg' %}">
                            </button>
                        </span>
                        <div id="search-result-container w-100%"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endcomment %}


    <section id="conversion" class="flex-grow py-4" style="background: url('{% static 'homepage-texture-background.svg' %}') top/contain repeat-y;">   
        <div class="container-fluid">
            <div class="row" >        
                <div class="col-12 mb-3"><h2 class="brand-text">{{title}}</h2></div>
                {% for obj in object_list %}
                    <div class="col-6 col-lg-4 mb-5">
                        <div class="card border-0 text-decoration-none shadow" >
                            <div class="d-flex flex-column align-items-center text-center align-middle bg-brand h-200 w-100 px-3" 
                            style="background:url('{% static "brand-background.svg" %}') no-repeat; background-position-x: right;
            background-position-y: bottom;">
                                <div class="my-auto text-white">
                                    <i class="fas fa-2x fa-trophy mb-3"></i>
                                    <h5 class="">{{obj.course}}</h5>
                                </div>
                            </div>
                          
                            <div class="d-flex flex-row justify-content-between card-body">
                                <a href="{% url 'courses:show-certificate' slug=obj.course.slug %}" class="btn btn-outline-secondary btn-sm" target="_blank" rel="noopener">Ver certificado</a>
                                <a href="{% url 'courses:show-certificate' slug=obj.course.slug %}?download=true" class="btn btn-outline-secondary btn-sm">Descargar certificado</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <section id="conversion" class="flex-grow bg-white shadow py-5">   
        <div class="container-fluid">
            <div class="row" >   
                <div class="col-3 text-center">
                    <img class="w-75 ml-auto" src="{% static 'icons/teaching-ad.png' %}" alt="Sucursal Digital de Paraíso Resort">
                </div>
                <div class="col-12 col-md-6 my-auto">
                    <h3 class="brand-text d-inline-block">Enseña en línea</h3>
                    <p class="mb-0">Comparte tus conocimientos y gana prestigio e ingresos extra. Contáctanos y dinos que curso o conferencia te gustaría impartir.</p>
                </div>
                <div class="col-12 col-md-3 my-auto">
                    <a href="" class="btn btn-outline-primary btn-block btn-xlg mx-auto">Contáctanos</a>
                </div>
            </div>
        </div>
    </section>

   
{% endblock content %}

{% block javascript %}
{% endblock javascript %}




{% comment %}
  nutricion en el paciente diabetico
  cuidado hijos
  hipertencion
  Soporte Nutricional en paciente postquirurgico.
  Como leer un electrocardiograma
{% endcomment %}